name: "Gradle build"

on:
  release:
    types:
      - created
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - 'test-branch'
      - 'main'
      - 'development'
      - 'release/**'
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
jobs:
  java-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 21 microsoft
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
  gradle-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle and run build
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - java-job
      - gradle-job
    #todo: calculate version and push tags
    #todo: cache gradle packages
    #todo setup docker context
    #todo: setup docker build
    #todo: setup gcloud NP
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Build with gradle wrapper
        run: ./gradlew build